//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public int idDir { get; set; }
        public Nullable<int> lon { get; set; }
        public Nullable<int> lat { get; set; }
        public Nullable<int> idUser { get; set; }
        public string nombre { get; set; }
    }
}
