//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platillosPedidos
    {
        public int idPlatPed { get; set; }
        public Nullable<int> idPed { get; set; }
        public Nullable<int> idPlat { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<float> subtotal { get; set; }
    }
}
