//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platillos
    {
        public int idPlatillo { get; set; }
        public Nullable<int> idRes { get; set; }
        public string nombre { get; set; }
        public string descp { get; set; }
        public Nullable<float> price { get; set; }
        public string imgPath { get; set; }
        public string categoria { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<float> subtotal { get; set; }
    }
}
