//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiboMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public int idDir { get; set; }
        public Nullable<int> lon { get; set; }
        public Nullable<int> lat { get; set; }
        public Nullable<int> idUser { get; set; }
        public string nombre { get; set; }
    }
}
