//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiboMarket.Models
{
    using SQLite;
    using System;
    using System.Collections.Generic;
    
    public partial class platillosPedidos
    {
        [PrimaryKey]
        public int idPlatPed { get; set; }
        public Nullable<int> idPed { get; set; }
        public Nullable<int> idPlat { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<float> subtotal { get; set; }
    }
}
