//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiboMarket.Models
{
    using Android.Widget;
    using Cibo.Models;
    using SQLite;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using Xamarin.Forms;

    public partial class platillos
    {
        [PrimaryKey]
        public int idPlatillo { get; set; }
        public Nullable<int> idRes { get; set; }
        public string nombre { get; set; }
        public string descp { get; set; }
        public Nullable<float> price { get; set; }
        public string imgPath { get; set; }
        public string categoria { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<float> subtotal { get; set; }



        
    }
}
