//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiboMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restauranteUsuario
    {
        public int idRU { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idRest { get; set; }
        public Nullable<bool> isFav { get; set; }
        public string imgFav { get; set; }
    }
}
